version: "3.8"

volumes:
  redis_data:
  mariadb_data:

services:

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mariadb:
    image: mariadb:10.3.28
    environment:
      MYSQL_ROOT_PASSWORD:  "purser"
      MYSQL_DATABASE: "purser"
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
